### ISSUE TITLE
Could not load 'plugins\CitizensBooks-2.4.0.jar'

### ISSUE THREAD

**Issue by M4rtyn4** [NicoNekoDev/AstralBooks#4]
`[22:29:54] [Server thread/ERROR]: Could not load 'plugins\CitizensBooks-2.4.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `ro.nicuch.citizensbooks.CitizensBooks'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: ro.nicuch.citizensbooks.CitizensBooks
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[spigot-1.12.2.jar:git-Spigot-c5afb9f-21d5f75]
	... 7 more`

I'm getting this error after updating to 2.4.0.
2.3.9 can load without any problems.

**Comment by VoidLock92** [comment]
Same thing happening here, identical.

**Comment by NicoNekoDev** [comment]
Ups, I forgot to update main class name in plugin.yml

**Comment by M4rtyn4** [comment]
You sure you uploaded fixed file on Spigot?
I just got it from there and I still get the same error.
:(

**Comment by NicoNekoDev** [comment]
Yep, my bad. I swear I copy-pasted the plugin to desktop, but somehow Chrome didn't think that too (I guess). Well now the right version is up.
Or maybe that happens when you just come from work and you're tired, but you try to fix only one small last thing.
